### PR TITLE
Add support for pointer fields on structs

### PR DESCRIPTION
**Pull request by c2h5oh**
+ minor cleanup on the last commit for pointer fields

### CODE REVIEW

**Comment by annismckenzie** [comment]
Can you add a test to `eval_test.go`? That'd be awesome.

**Comment by c2h5oh** [comment]
sure thing - I'll write one now

**Comment by c2h5oh** [comment]
Test added

**Comment by annismckenzie** [comment]
Looks good, merging! :dancer:

**Pull request merged**
