### PR TITLE
Fix inconsistency with add operator, Added switch/case, Added default pipeline, Filter block with format function

### PR DESCRIPTION
**Pull request by maxime1907**
#93

### CODE REVIEW

**Comment by annismckenzie** [comment]
I rebased all of your work on top of the current master and reworked the commits some (dropping unnecessary merges, combining fixup commits). I went through the code yesterday and understand only half of it so I'll add some tests next. I might also split out the + operator changes as I mentioned in #93.

**Comment by annismckenzie** [comment]
Sorry that this takes so long but I'm not comfortable with merging this before I add at least a couple more test cases. I will do that this week.

**Comment by stedounet** [comment]
Hi !
Any plan on this ? Looking forward for it !

**Comment by tooolbox** [comment]
@annismckenzie ping!  :)

**Comment by Dexus** [comment]
ping @annismckenzie <3

**Comment by annismckenzie** [comment]
@tooolbox @Dexus I can do a rebase of this branch against the current master but then it'd be up to someone else to test this as I currently don't have the bandwidth to make sure this monster of a PR is good to go. The project where I used Jet extensively was replaced just a couple days ago after working on a single page application for the last 2 years… so I'm effectively not using Jet anymore in production. Any thoughts?

**Comment by annismckenzie** [comment]
Sigh, made a mistake with a push. Don't really know what happened here on the upstream. I rebased everything and will open up a new PR. Sorry guys.

**Comment by tooolbox** [comment]
No prob @annismckenzie 

Sure, don't mind doing some testing.

**Comment by annismckenzie** [comment]
That's greatly appreciated! I'll try to write up some more tests for the parts that don't have any yet (default etc.). The branch in #136 is rebased against the current master with Go modules on v3. Can you take that for a spin?

**Comment by Dexus** [comment]
@annismckenzie will take it for a test in our dev.

**Pull request closed without merging**
